[2020-09-21T17:28:17.820] [ERROR] application - ReferenceError: Project is not defined
    at _callee3$ (E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:27)
    at tryCatch (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:117:21)
    at step (E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:191)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:437
    at new Promise (<anonymous>)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:99
    at E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:1
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at cors (E:\self_prj\koa_mongo_wool\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:15)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-09-21T17:28:17.835] [ERROR] application - ReferenceError: Project is not defined
    at _callee3$ (E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:27)
    at tryCatch (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:117:21)
    at step (E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:191)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:437
    at new Promise (<anonymous>)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:99
    at E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:1
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at cors (E:\self_prj\koa_mongo_wool\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:15)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-09-21T17:29:06.413] [ERROR] application - ReferenceError: Project is not defined
    at _callee3$ (E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:27)
    at tryCatch (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:117:21)
    at step (E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:191)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:437
    at new Promise (<anonymous>)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:99
    at E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:1
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at cors (E:\self_prj\koa_mongo_wool\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:15)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-09-21T17:29:06.415] [ERROR] application - ReferenceError: Project is not defined
    at _callee3$ (E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:27)
    at tryCatch (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:117:21)
    at step (E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:191)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:437
    at new Promise (<anonymous>)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:99
    at E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:1
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at cors (E:\self_prj\koa_mongo_wool\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:15)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-09-21T17:29:37.955] [ERROR] application - ReferenceError: Project is not defined
    at _callee3$ (E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:27)
    at tryCatch (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.<computed> [as next] (E:\self_prj\koa_mongo_wool\node_modules\_regenerator-runtime@0.10.5@regenerator-runtime\runtime.js:117:21)
    at step (E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:191)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:437
    at new Promise (<anonymous>)
    at E:\self_prj\koa_mongo_wool\appApi\fourWeb_original.js:3:99
    at E:/self_prj/koa_mongo_wool/appApi/fourWeb_original.js:77:1
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at cors (E:\self_prj\koa_mongo_wool\node_modules\_koa2-cors@2.0.6@koa2-cors\dist\index.js:91:15)
    at dispatch (E:\self_prj\koa_mongo_wool\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7
[2020-09-21T17:48:03.622] [ERROR] application - SyntaxError: Unexpected token m in JSON at position 1
    at JSON.parse (<anonymous>)
    at parse (E:\self_prj\koa_mongo_wool\node_modules\_co-body@6.0.0@co-body\lib\json.js:57:17)
    at AsyncFunction.module.exports [as json] (E:\self_prj\koa_mongo_wool\node_modules\_co-body@6.0.0@co-body\lib\json.js:41:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at parseBody (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:100:14)
    at bodyParser (E:\self_prj\koa_mongo_wool\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:85:19)
    at E:\self_prj\koa_mongo_wool\node_modules\_koa-log4@2.3.2@koa-log4\koa-logger.js:86:7 {
  status: 400,
  body: "{myId:'416758f0-6cf6-4a2e-abe2-8ddbdb71a7aa'}"
}
